name: Fetch Info

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    services:
      vpn:
        image: larryteal/cwcid:latest
        options: >-
          --cap-add=NET_ADMIN
          --sysctl net.ipv6.conf.all.disable_ipv6=0
          --sysctl net.ipv4.conf.all.src_valid_mark=1
          --health-cmd="curl -fsSL https://www.cloudflare.com/cdn-cgi/trace/ | grep warp=on || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5
          --health-start-period=5s
        # --log-driver=none

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_OUTPUT
        
      - name: Run task
        run: |
          mkdir -p briefings
          docker run --rm --network=container:${{ job.services.vpn.id }} -v $PWD:/app -w /app larryteal/curlpy:latest python main.py $REFRESH_TOKEN $INSTALL_ID $USER_AGENT $LOGIN_URL $BRIEFINGS_URL
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          INSTALL_ID: ${{ secrets.INSTALL_ID }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          BRIEFINGS_URL: ${{ secrets.BRIEFINGS_URL }}
      
      - name: Commit and push new info file
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add briefings/*.json
          git commit -m "Add info for ${{ steps.get-timestamp.outputs.timestamp }} UTC" || echo "Nothing to commit"
          git push    
